<a href="https://colab.research.google.com/github/Jkkcesar/Ciencia_de_Dados_e_Aprendizagem_de_Maquina/blob/main/Capitulo2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nome: Júlio César | UDF | Ssitemas de Informação |Ciência de Dados   

Python para Ciência de Dados

Contents

* Manipulação de Dados Tabulares com Pandas - Funções Básicas

* Tipos de Dados com Pandas

* Renomeando Colunas

* Selecionando Linhas e Colunas

* Adicionando e Removendo Colunas

* Operações Básicas - Consultas

* Operações Básicas - Ordenação

* Operações Básicas - Combinando DataFrames

* Operações Básicas - Salvando DataFrames

* Manipulação de Dados Tabulares com Pandas - Funções

* BásicasPrint to PDF

Manipulação de Dados Tabulares com Pandas - Funções
Básicas

In [5]:
import pandas as pd

In [6]:
cidades = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00],
        ['São PAulo', 'São Carlos', 254484, 1508.00],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
        ['Paraná', 'Curitiba', 1963726, 2293.00],
        ['São Paulo', 'Campinas', 122323, 1710.00]
    ], columns=['Estado', 'Cidade', 'Habitantes', 'Salário-médio'])
cidades

           Estado         Cidade  Habitantes  Salário-médio
0          Paraná       Londrina      575377         1356.0
1       São PAulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas      122323         1710.0

In [29]:
cidades.head(2)

      Estado      Cidade  N Habitantes  Salário-médio
0     Paraná    Londrina        575377         1356.0
1  São PAulo  São Carlos        254484         1508.0

In [28]:
cidades.tail(2)

      Estado    Cidade  N Habitantes  Salário-médio
3     Paraná  Curitiba       1963726         2293.0
4  São Paulo  Campinas        122323         1710.0

In [27]:
cidades.shape

(5, 4)

In [26]:
cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   N Habitantes   5 non-null      int64
 3   Salário-médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [25]:
cidades.columns

Index(['Estado', 'Cidade', 'N Habitantes', 'Salário-médio'], dtype='object')

In [65]:
cidades['Salário-médio'].describe()

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salário-médio, dtype: float64

Tipos de Dados com Pandas

In [44]:
display(cidades.dtypes)

cidades.info()

Estado                   object
Cidade                   object
N Habitantes            float64
Salário-médio           float64
data             datetime64[ns]
Data             datetime64[ns]
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   N Habitantes   5 non-null      float64
 3   Salário-médio  5 non-null      float64
 4   data           5 non-null      datetime64[ns]
 5   Data           5 non-null      datetime64[ns]
dtypes: datetime64[ns](2), float64(2), object(2)
memory usage: 372.0+ bytes

In [42]:
cidades['N Habitantes'] = cidades['N Habitantes'].astype('float64')

cidades.dtypes

Estado                   object
Cidade                   object
N Habitantes            float64
Salário-médio           float64
data             datetime64[ns]
Data             datetime64[ns]
dtype: object

In [41]:
cidades['data'] = [
    '3-8-2021',
    '3-9-2021',
    '3-10-2021',
    '3-11-2021',
    '3-12-2021'
]

cidades['data'] = pd.to_datetime(
    cidades['data'],
    format='%d-%m-%Y'
)

cidades

,Estado,Cidade,N Habitantes,Salário-médio,data,Data
0,Paraná,Londrina,575377.0,1356.0,2021-08-03,2021-08-03
1,São PAulo,São Carlos,254484.0,1508.0,2021-09-03,2021-09-03
2,Santa Catarina,Florianópolis,508826.0,1798.0,2021-10-03,2021-10-03
3,Paraná,Curitiba,1963726.0,2293.0,2021-11-03,2021-11-03
4,São Paulo,Campinas,122323.0,1710.0,2021-12-03,2021-12-03

In [45]:
cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y') # Dia, Mês, Ano
cidades # Novo Formato

,Estado,Cidade,N Habitantes,Salário-médio,data,Data
0,Paraná,Londrina,575377.0,1356.0,2021-08-03,03-08-2021
1,São PAulo,São Carlos,254484.0,1508.0,2021-09-03,03-09-2021
2,Santa Catarina,Florianópolis,508826.0,1798.0,2021-10-03,03-10-2021
3,Paraná,Curitiba,1963726.0,2293.0,2021-11-03,03-11-2021
4,São Paulo,Campinas,122323.0,1710.0,2021-12-03,03-12-2021

Renomeando Colunas

In [50]:
cidadesHab = cidades[['N Habitantes', 'Salário-médio']]
cidadesHab

   N Habitantes  Salário-médio
0      575377.0         1356.0
1      254484.0         1508.0
2      508826.0         1798.0
3     1963726.0         2293.0
4      122323.0         1710.0

In [52]:
cidades.loc[[1, 2]]

,Estado,Cidade,N Habitantes,Salário-médio,data,Data
1,São PAulo,São Carlos,254484.0,1508.0,2021-09-03,03-09-2021
2,Santa Catarina,Florianópolis,508826.0,1798.0,2021-10-03,03-10-2021

In [54]:
cidades.iloc[1:3]

,Estado,Cidade,N Habitantes,Salário-médio,data,Data
1,São PAulo,São Carlos,254484.0,1508.0,2021-09-03,03-09-2021
2,Santa Catarina,Florianópolis,508826.0,1798.0,2021-10-03,03-10-2021

In [55]:
cidades.iloc[:, 0:2]

           Estado         Cidade
0          Paraná       Londrina
1       São PAulo     São Carlos
2  Santa Catarina  Florianópolis
3          Paraná       Curitiba
4       São Paulo       Campinas

In [56]:
cidades.iloc[1:3, :3]

           Estado         Cidade  N Habitantes
1       São PAulo     São Carlos      254484.0
2  Santa Catarina  Florianópolis      508826.0

In [57]:
cidades.iloc[:, [1, 3, 0, 2]]

          Cidade  Salário-médio          Estado  N Habitantes
0       Londrina         1356.0          Paraná      575377.0
1     São Carlos         1508.0       São PAulo      254484.0
2  Florianópolis         1798.0  Santa Catarina      508826.0
3       Curitiba         2293.0          Paraná     1963726.0
4       Campinas         1710.0       São Paulo      122323.0

Adicionando e Removendo Colunas

In [58]:
cidades.insert(2, 'sigla', ['PR', 'SP', 'SC', 'PR', 'SP'])
cidades.insert(2, 'siglaRepetida', cidades['sigla'])
cidades

,Estado,Cidade,siglaRepetida,sigla,N Habitantes,Salário-médio,data,Data
0,Paraná,Londrina,PR,PR,575377.0,1356.0,2021-08-03,03-08-2021
1,São PAulo,São Carlos,SP,SP,254484.0,1508.0,2021-09-03,03-09-2021
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,2021-10-03,03-10-2021
3,Paraná,Curitiba,PR,PR,1963726.0,2293.0,2021-11-03,03-11-2021
4,São Paulo,Campinas,SP,SP,122323.0,1710.0,2021-12-03,03-12-2021

In [61]:
if 'siglaRepetida' in cidades.columns:
    cidades.pop('siglaRepetida')
    print("Coluna 'siglaRepetida' removida.")
else:
    print("Coluna 'siglaRepetida' já não existe no DataFrame.")
cidades

Coluna 'siglaRepetida' já não existe no DataFrame.

,Estado,Cidade,sigla,N Habitantes,Salário-médio,data,Data
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03,03-08-2021
1,São PAulo,São Carlos,SP,254484.0,1508.0,2021-09-03,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03,03-11-2021
4,São Paulo,Campinas,SP,122323.0,1710.0,2021-12-03,03-12-2021

Operações Básicas - Consultas

In [68]:
cidades.query('`Salário-médio` > 1400.0')

,Estado,Cidade,sigla,N Habitantes,Salário-médio,data,Data
1,São PAulo,São Carlos,SP,254484.0,1508.0,2021-09-03,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03,03-11-2021
4,São Paulo,Campinas,SP,122323.0,1710.0,2021-12-03,03-12-2021

In [69]:
cidades.query('Estado == "São Paulo"')

,Estado,Cidade,sigla,N Habitantes,Salário-médio,data,Data
4,São Paulo,Campinas,SP,122323.0,1710.0,2021-12-03,03-12-2021

In [70]:
cidades.query('`N Habitantes` > 500000 and `N Habitantes` < 1300000')

,Estado,Cidade,sigla,N Habitantes,Salário-médio,data,Data
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03,03-08-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03,03-10-2021

Operações Básicas - Ordenação

In [74]:
cidades.sort_values(by='Cidade', inplace=True)
cidades

,Estado,Cidade,sigla,N Habitantes,Salário-médio,data,Data
4,São Paulo,Campinas,SP,122323.0,1710.0,2021-12-03,03-12-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03,03-11-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03,03-10-2021
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03,03-08-2021
1,São PAulo,São Carlos,SP,254484.0,1508.0,2021-09-03,03-09-2021

In [76]:
cidades.sort_values(by='Salário-médio', inplace=True)
cidades

,Estado,Cidade,sigla,N Habitantes,Salário-médio,data,Data
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03,03-08-2021
1,São PAulo,São Carlos,SP,254484.0,1508.0,2021-09-03,03-09-2021
4,São Paulo,Campinas,SP,122323.0,1710.0,2021-12-03,03-12-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03,03-10-2021
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03,03-11-2021

Operações Básicas - Combinando DataFrames

In [77]:
cidadesSalarios = pd.DataFrame(
 [
 ['Paraná', 'Londrina', 1356.00],
 ['São Paulo', 'São Carlos', 1508.00],
 ['Santa Catarina', 'Florianópolis', 1798.00],
 ['Paraná', 'Curitiba', 2293.00],
 ['São Paulo', 'Campinas', 1710.00]
 ], columns=['estado', 'cidade', 'salarioMedio'])
cidadesSalarios

           estado         cidade  salarioMedio
0          Paraná       Londrina        1356.0
1       São Paulo     São Carlos        1508.0
2  Santa Catarina  Florianópolis        1798.0
3          Paraná       Curitiba        2293.0
4       São Paulo       Campinas        1710.0

In [78]:
cidades_pop = pd.DataFrame(
 [
 ['Londrina', 575377],
 ['São Carlos', 254484],
 ['Florianópolis', 508826],
 ['Curitiba', 1963726],
 ['Campinas', 1223237]
 ], columns=['Cidade', 'Habitantes'])
cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [81]:
pd.merge(left=cidadesSalarios, right=cidades_pop, left_on="cidade", right_on="Cidade")

           estado         cidade  salarioMedio         Cidade  Habitantes
0          Paraná       Londrina        1356.0       Londrina      575377
1       São Paulo     São Carlos        1508.0     São Carlos      254484
2  Santa Catarina  Florianópolis        1798.0  Florianópolis      508826
3          Paraná       Curitiba        2293.0       Curitiba     1963726
4       São Paulo       Campinas        1710.0       Campinas     1223237

In [83]:
pd.merge(left=cidadesSalarios, right=cidades_pop, left_on="cidade", right_on="Cidade", how="outer")

           estado         cidade  salarioMedio         Cidade  Habitantes
0       São Paulo       Campinas        1710.0       Campinas     1223237
1          Paraná       Curitiba        2293.0       Curitiba     1963726
2  Santa Catarina  Florianópolis        1798.0  Florianópolis      508826
3          Paraná       Londrina        1356.0       Londrina      575377
4       São Paulo     São Carlos        1508.0     São Carlos      254484

In [84]:
cidades_df1 = pd.DataFrame(
 [
 ['Londrina', 575377],
 ['São Carlos', 254484],
 ['Florianópolis', 508826],
 ], columns=['Cidade', 'Habitantes'])
cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [85]:
cidades_df2 = pd.DataFrame(
 [
 ['Curitiba', 1963726],
 ['Campinas', 1223237]
 ], columns=['Cidade', 'Habitantes'])
cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [86]:
pd.concat([cidades_df1, cidades_df2], ignore_index=True)

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

Operações Básicas - Salvando DataFrames

In [87]:
cidades.to_csv("myDf.csv")
cidades.to_html("myDf.html")
cidades.to_json("myDf.json")